name: push-jestest

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - name: npm install
        run: npm install
      - name: Run eslint
        run: npx eslint
      - name: Run Jest
        run: npm test
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
